tspmap/mapaubigeo/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from . import views

urlpatterns = [
    path('', views.viewMap, name='viewMap'),
    re_path(r'^cp_filter/$', views.filter_cp, name='cp_filter'),
]

tspmap/tspmap/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mapa/', include('mapaubigeo.urls')),
]

tspmap/mapaubigeo/models.py
from django.db import models
TIPO_UBIGEO = (
    ('', '--'),
    ('0', 'No es capital'),
    ('1', 'Departamental'),
    ('2', 'Provincial'),
    ('3', 'Distrital'),
)

EMPTY_CP = (
    ('', '--'),
)

# Create your models here.
class CentroPoblado(models.Model):
    codigo = models.CharField(max_length=200)
    nombre_cp = models.CharField(max_length=200)
    distrito = models.CharField(max_length=200)
    provincia = models.CharField(max_length=200)
    region = models.CharField(max_length=200)
    latitud = models.DecimalField(max_digits=9, decimal_places=7)
    longitud = models.DecimalField(max_digits=9, decimal_places=7)
    tipo = models.CharField(max_length=1, choices=TIPO_UBIGEO)
    
    def __str__(self):
        return 'CP: {0} DS:{1} PR:{2} RG: {3}'.format(self.nombre_cp, self.distrito, self.provincia, self.region)

tspmap/mapaubigeo/forms.py
from django import forms
from .models import CentroPoblado
from .models import TIPO_UBIGEO

class UbigeoForm(forms.Form):
    tipoCp = forms.CharField(label='Tipo de Centro Poblado',
                            widget=forms.Select(
                            choices=TIPO_UBIGEO,
                            attrs={'class': 'form-control'}))

    ubigeoOrigen = forms.CharField(label='Ubigeo Origen',
                                   widget=forms.Select(
                                   choices=CentroPoblado.objects.none(),                                        
                                   attrs={'class': 'form-control', 'disabled':'true'}))

    ubigeoDestino = forms.CharField(label='Ubigeo Destino',
                                    widget=forms.Select(
                                    choices=CentroPoblado.objects.none(),                                        
                                    attrs={'class': 'form-control', 'disabled':'true'}))

tspmap/mapaubigeo/views.py
from django.shortcuts import render, get_list_or_404
from .forms import UbigeoForm
from .models import CentroPoblado
from django.conf import settings
from django.core import serializers
import json
from django.http import HttpResponse

# Create your views here.
def viewMap(request):
    if request.method == 'POST':
        form = UbigeoForm(request.POST)
        ubigeo_post = []
        position_val = []

        if form.is_valid():
            ubigeo_post.append(form.cleaned_data['ubigeoOrigen'])
            ubigeo_post.append(form.cleaned_data['ubigeoDestino'])

            cp_queryset = get_list_or_404(CentroPoblado, pk__in=ubigeo_post)

            for cp in cp_queryset:
                position_val.append({'nombre_cp': cp.nombre_cp, 
                                     'latitud': cp.latitud, 
                                     'longitud':cp.longitud})


            return render(request, 'mapaubigeo/index.html', 
                         {'form': form,
                           'position_render': position_val,
                           'origen': cp_queryset[0],
                           'destino': cp_queryset[1],
                           'GOOGLE_API_KEY': settings.GOOGLE_API_KEY
                         })
    else:
        form = UbigeoForm

    return render(request, 'mapaubigeo/index.html', {'form': form})


def filter_cp(request):
    cp_id = None
    return_list = []
    if request.method == 'GET':
        cp_id = request.GET['cp_id']
    
    if cp_id:
        cp_list = CentroPoblado.objects.filter(tipo=cp_id)
        cp_list = [{'id': c.id, 
                    'list': 'CP: {0} DS:{1} PR:{2} RG: {3}'.format(c.nombre_cp, c.distrito, c.provincia, c.region)} 
                    for c in cp_list]
        data = json.dumps({"cp_list": cp_list})

    return HttpResponse(data, content_type='application/json')

tspmap/mapaubigeo/templates/mapaubigeo/index.html
<!DOCTYPE html>
<html>

<head>
   <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
   <title>Ubigeos | Mapa </title>
   <script src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLE_API_KEY }}" type="text/javascript"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
   <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
   <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">   
</head>

<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a href="" class="navbar-brand">TSPMAP</a>
            </div>
        </div>
    </nav>

    <div class="container">
        <form action="" method="post">
            {% csrf_token %}
                <div class="form-group">
                    {% for f in form.visible_fields %}
                        {{ f.label_tag }}
                        {{ f }}
                    {% endfor %}
                </div>
                <input type="submit" class="btn btn-primary" value="Enviar">
        </form>
        <br>
        
        {% if position_render %}
            <div>
                <h4 id="origen"></h4>
            </div>
            <div>
                <h4 id="destino"></h4>
            </div>   
            </br>
            <div id="map" style="width: 500px; height: 400px;"></div>
        {% endif %}
    </div>

   <script type="text/javascript">
       var locations = [];
       var locations_polyline  = [];

        {% for p in position_render %}
            locations.push([
                '{{ p.nombre_cp }}', {{ p.latitud }}, {{ p.longitud }}
            ]);

            locations_polyline.push({
                lat: {{ p.latitud }}, lng: {{ p.longitud }}
            });            
        {% endfor %}

        var map = new google.maps.Map(document.getElementById('map'), {
           zoom: 5,
           center: new google.maps.LatLng(-10.151093, -75.311132),
           mapTypeId: google.maps.MapTypeId.ROADMAP
        });

        var infowindow = new google.maps.InfoWindow();

        var marker, i;

        for (i = 0; i < locations.length; i++) {
           marker = new google.maps.Marker({
               position: new google.maps.LatLng(locations[i][1], locations[i][2]),
               map: map
           });

           google.maps.event.addListener(marker, 'click', (function(marker, i) {
               return function() {
                   infowindow.setContent(locations[i][0]);
                   infowindow.open(map, marker);
               }
           })(marker, i));
        }


        var flightPath = new google.maps.Polyline({
           path: locations_polyline,
           geodesic: true,
           strokeColor: '#FF0000',
           strokeOpacity: 1.0,
           strokeWeight: 2
        });

        flightPath.setMap(map);
        document.getElementById('id_tipoCp').value="";
        document.getElementById('origen').innerText = "{{origen}}";
        document.getElementById('destino').innerText = "{{destino}}";

   </script>
   <script>
        $(document).ready(function() {
            var ubOrigen = $('#id_ubigeoOrigen');
            var ubDestino = $('#id_ubigeoDestino');
            var tipoCp = $("#id_tipoCp");
            $('#id_tipoCp option[value=" "]').attr("selected",true);


            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie !== '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }
            var csrftoken = getCookie('csrftoken');

            function csrfSafeMethod(method) {
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }

            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });

            $("#id_tipoCp").on("change", function() {
                ubOrigen.find('option').remove();                          
                ubDestino.find('option').remove();      
                $('<option>').val('').text('').appendTo(ubOrigen).attr("selected", true);     
                $('<option>').val('').text('').appendTo(ubDestino).attr("selected", true);   
                                              
                if(this.value != ''){                       
                    $.get('/mapa/cp_filter/', {cp_id: this.value}, function(data){        
                        if(data.cp_list.length>0){
                            $.each(data.cp_list, function(key, value) {       
                                ubOrigen.prop('disabled', false);
                                ubDestino.prop('disabled', false);
                                $('<option>').val(value.id).text(value.list).appendTo(ubOrigen);     
                                $('<option>').val(value.id).text(value.list).appendTo(ubDestino);     
                            });  
                        } else {
                            ubOrigen.prop('disabled', true);
                            ubDestino.prop('disabled', true);                                                 
                        }                                          
                    });
                } else {
                    ubOrigen.prop('disabled', true);
                    ubDestino.prop('disabled', true);                       
                }
            });      
        });
   </script>
</body>

</html>